apiVersion: v1
kind: PersistentVolume
metadata:
  name: openshift-image-registry-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.76.168.100
    path: /nfs/storage

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openshift-image-registry-pvc
  namespace: openshift-image-registry
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: openshift-image-registry-pv
  volumeMode: Filesystem