apiVersion: v1
kind: Secret
metadata:
  name: loki-s3
  namespace: netobserv   
stringData:
  access_key_id: 1
  access_key_secret: 1
  bucketnames: loki-network-b16a493a-1c1b-4712-80d7-9723e0a8ba90
  endpoint: https://s3-openshift-storage.apps.hub.redhatkrsa.com