apiVersion: v1
kind: Secret
metadata:
  name: loki-s3
  namespace: netobserv   
stringData:
  access_key_id: 
  access_key_secret: 
  bucketnames: quay-kako
  endpoint: https://s3.us-east-1.amazonaws.com