apiVersion: v1
metadata:
  name: 'ocp1'
featureSet: TechPreviewNoUpgrade
additionalTrustBundlePolicy: Proxyonly
baseDomain: redhatkrsa.com
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
  platform:
    vsphere:
      cpus:  8
      coresPerSocket:  2
      memoryMB:  16384
      osDisk:
        diskSizeGB: 120
      zones:
      - "vmzone1"
      - "vmzone2"
compute:
- hyperthreading: Enabled
  name: 'worker'
  replicas: 2
  platform:
    vsphere:
      cpus:  12
      coresPerSocket:  2
      memoryMB:  24576
      osDisk:
        diskSizeGB: 120
networking:
  networkType: OVNKubernetes
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.76.168.0/23
  serviceNetwork:
  - 172.30.0.0/16
platform:
  vsphere:
    failureDomains:
    - name: vmzone1
      region: region
      server: vcenter.redhatkrsa.com
      topology:
        computeCluster: /Datacenter/host/Cluster
        datacenter: Datacenter
        datastore: /Datacenter/datastore/host6nfs
        networks:
        - VM Network
      zone: zone1
    - name: vmzone2
      region: region
      server: vcenter.redhatkrsa.com
      topology:
        computeCluster: /Datacenter/host/Cluster2
        datacenter: Datacenter
        datastore: /Datacenter/datastore/host6nfs
        networks:
        - VM Network
      zone: zone2
    vCenter: vcenter.redhatkrsa.com
    username: administrator@vsphere.local
    password: fpemgot1!KoreaSateam
    datacenter: Datacenter
    defaultDatastore: host6nfs
    cluster: Cluster
    apiVIP: 10.76.168.103
    ingressVIP: 10.76.168.104
    network: 'VM Network'
    diskType: 'thin'
    hosts:
    - role: bootstrap
      networkDevice: 
        ipAddrs:
        - 10.76.168.199/23
        gateway: 10.76.169.254
        nameservers:
        - 10.76.168.7
    - role: control-plane
      networkDevice:
        ipAddrs:
        - 10.76.168.191/23
        gateway: 10.76.169.254
        nameservers:
        - 10.76.168.7
    - role: control-plane
      networkDevice:
        ipAddrs:
        - 10.76.168.192/23
        gateway: 10.76.169.254
        nameservers:
        - 10.76.168.7
    - role: control-plane
      networkDevice:
        ipAddrs:
        - 10.76.168.193/23
        gateway: 10.76.169.254
        nameservers:
        - 10.76.168.7
    - role: compute
      networkDevice:
        ipAddrs:
        - 10.76.168.194/23
        gateway: 10.76.169.254
        nameservers:
        - 10.76.168.7
    - role: compute
      networkDevice:
        ipAddrs:
        - 10.76.168.195/23
        gateway: 10.76.169.254
        nameservers:
        - 10.76.168.7
pullSecret: "" # skip, hive will inject based on it's secrets
sshKey: |-
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC1CVATnZslpB97D4UTF22tpL98n7Y988+aw6XbYPf/zQ1YmpQaad4+S8QdbKMInzrDv60BCCmmTbQGIgD2Ag9oufRwmtWf1dBbIERS46Nj8QKoNAHfH/xBqzvfyF4x5IM2LNq9y6QdDFgyBkpT4kVgPUHc7fICSPzR51vM9IVi86HojNMC5AOc/0g2kd/a1fHK3hC4wS/kGIthsNErg3lMfLORCZ55bSwUBXfm7B89R80FTx/H9DF1XpJJ2m8ZXa5Q/OXZnBwYyGO2ii+WWoMhe2gzlVpgXHMb6H7xpOAlO9nz86XJ0ke9740enpuHkEcIUVpsI7y0CO0NmmBqFPWc39mR2iiV2UJ9/RM3ISbHosPZyjUyMKJjPFHPERWALW5Fg8doyr/FChP+H78mVdtjX0ei29JF8jwvFpMlTdKIkklLGmz2vFdL6pi0tQjRIHOSS0GSJ2TMT1kut6d3iP4/A9PTRNS5Htndh5QgXEs8MRdv9/bJtc5WCRxFWr1qzE8= ocp1@bastion1.hub.redhatkrsa.com