apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: auth-cluster-config
  namespace: default
spec:
  disabled: false
  remediationAction: enforce
  policy-templates:
# Create ns1, ns2 project (namespace)
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: create-ns1-project
        spec:
          remediationAction: inform # will be overridden by remediationAction in parent policy
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: ns1
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: create-ns2-project
        spec:
          remediationAction: inform # will be overridden by remediationAction in parent policy
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: ns2
# Create RollBinding
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: ns1-edit-tempdev1
        spec:
          remediationAction: inform  # will be overridden by remediationAction in parent policy
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: RoleBinding
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: ns1-edit-tempdev1
                  namespace: ns1
                subjects:
                  - kind: User
                    apiGroup: rbac.authorization.k8s.io
                    name: tempdev1
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: edit
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: ns2-edit-tempdev2
        spec:
          remediationAction: inform  # will be overridden by remediationAction in parent policy
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: RoleBinding
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: ns2-edit-tempdev2
                  namespace: ns2
                subjects:
                  - kind: User
                    apiGroup: rbac.authorization.k8s.io
                    name: tempdev2
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: edit
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: cluster-view-tempmon
        spec:
          remediationAction: inform  # will be overridden by remediationAction in parent policy
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: ClusterRoleBinding
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: cluster-view-tempmon
                subjects:
                  - kind: User
                    apiGroup: rbac.authorization.k8s.io
                    name: tempmon
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: view
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: auth-cluster-config-placement
  namespace: default
spec:
  clusterSets:
    - default
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: test
              operator: In
              values:
                - auth
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: auth-cluster-config-placement
  namespace: default
placementRef:
  name: auth-cluster-config-placement
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: auth-cluster-config
    apiGroup: policy.open-cluster-management.io
    kind: Policy
