apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: oauth-config
  namespace: default
spec:
  disabled: false
  remediationAction: enforce
  policy-templates:
# Create htpasswd secret for kadmin, kmon
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: create-htpasswd-secret
        spec:
          remediationAction: inform # will be overridden by remediationAction in parent policy
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: Secret
                apiVersion: v1
                metadata:
                  name: htpass-secret
                  namespace: openshift-config
                data:
                  htpasswd: >-
                    a2FkbWluOiQyeSQwNSRDUFMyTkguVTZtVXJqQ0txRmpnamN1OFhEdGhJdDdTRUkxb3kwdFk2YlEzSDgvZUFESkhzUwprbW9uOiQyeSQwNSRHUTJoNlBuT3QxUHhubG5NOXBzRTJlTThMS0NRY3VVMGd5Z2NjQXZLSFIzQWs1RzJqM1AzbQo=
                type: Opaque
# Configure OAuth
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: config-oauth
        spec:
          remediationAction: inform # will be overridden by remediationAction in parent policy
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: OAuth
                metadata:
                  name: cluster
                spec:
                  identityProviders:
                    - htpasswd:
                        fileData:
                          name: htpass-secret
                      mappingMethod: claim
                      name: htpasswd_provider
                      type: HTPasswd
# Create ClusterRollBinding for kadmin, kmon
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: cluster-admin-kadmin
        spec:
          remediationAction: inform  # will be overridden by remediationAction in parent policy
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: ClusterRoleBinding
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: cluster-admin-kadmin
                subjects:
                  - kind: User
                    apiGroup: rbac.authorization.k8s.io
                    name: kadmin
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: cluster-admin
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: view-kmon
        spec:
          remediationAction: inform  # will be overridden by remediationAction in parent policy
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: ClusterRoleBinding
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: view-kmon
                subjects:
                  - kind: User
                    apiGroup: rbac.authorization.k8s.io
                    name: kmon
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: view
# Delete kubeadmin
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: delete-kubeadmin
        spec:
          remediationAction: inform  # will be overridden by remediationAction in parent policy
          severity: high
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                kind: Secret
                apiVersion: v1
                metadata:
                  name: kubeadmin
                  namespace: kube-system
                data:
                  kubeadmin: >-
                    JDJhJDEwJFpTRHFuR05BQi5LMy50aVNGZEJuSS5hLlpyY0NubUxCbXFBQi5IR3IzeTdQMEd4bmsuM3Q2
                type: Opaque
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: oauth-config-placement
  namespace: default
spec:
  clusterSets:
    - default
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: environment
              operator: In
              values:
                - dev
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: oauth-config-placement
  namespace: default
placementRef:
  name: oauth-config-placement
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: oauth-config
    apiGroup: policy.open-cluster-management.io
    kind: Policy
