kind: Secret
apiVersion: v1
metadata:
  name: htpass-secret
  namespace: openshift-config
data:
  htpasswd: >-
    a2FkbWluOiQyeSQwNSRDUFMyTkguVTZtVXJqQ0txRmpnamN1OFhEdGhJdDdTRUkxb3kwdFk2YlEzSDgvZUFESkhzUwprbW9uOiQyeSQwNSRHUTJoNlBuT3QxUHhubG5NOXBzRTJlTThMS0NRY3VVMGd5Z2NjQXZLSFIzQWs1RzJqM1AzbQo=
type: Opaque