kind: Secret
apiVersion: v1
metadata:
  name: kubeadmin
  namespace: kube-system
data:
  kubeadmin: >-
    JDJhJDEwJFpTRHFuR05BQi5LMy50aVNGZEJuSS5hLlpyY0NubUxCbXFBQi5IR3IzeTdQMEd4bmsuM3Q2
type: Opaque