apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: mapping
spec:
  desiredState:
    ovn:
      bridge-mappings:
        - bridge: br-ex
          localnet: localnet1
          state: present
  nodeSelector:
    node-role.kubernetes.io/worker: ''



apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: localnet1
  namespace: vm-test
spec:
  config: |
    {
            "cniVersion": "0.3.1",
            "name": "localnet1",
            "type": "ovn-k8s-cni-overlay",
            "topology":"localnet",
            "mtu": 1300,
            "vlanID": 3001,
            "netAttachDefName": "vm-test/localnet1"
    }




