apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: br1-enp3s0-policy 
spec:
  desiredState:
    interfaces:
      - name: br1
        description: Linux bridge with enp3s0 as a port 
        type: linux-bridge 
        state: up 
        ipv4:
          enabled: false 
        bridge:
          options:
            stp:
              enabled: false 
          port:
            - name: enp3s0
  nodeSelector:
    node-role.kubernetes.io/worker: ""


# 참고

    { "cniVersion": "0.3.1", "name": "bridge-main", "type": "bridge", "bridge":
    "mybr1", "ipam": { "type": "host-local", "subnet": "10.76.168.0/23",
    "rangeStart": "10.76.168.221", "rangeEnd": "10.76.168.230" } }

apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    description: l2 connection for vms
  name: vlan0
  namespace: vm-test
spec:
  config: |-
    {
      "cniVersion": "0.4.0",
      "name": "vm-network",
      "type": "bridge",
      "bridge": "br1"
      "topology": "localnet",
      "netAttachDefName": "vm-test/vlan0"
    }


apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/br1
  name: vm-network
  namespace: vm-test
spec:
  config: '{"name":"vm-network","type":"bridge","cniVersion":"0.3.1","bridge":"br1","macspoofchk":true,"ipam":{},"preserveDefaultVlan":false}'