apiVersion: performance.openshift.io/v2
kind: PerformanceProfile
metadata:
  name: performance
spec:
  cpu:
    isolated: '8-23,32-47'
    reserved: '0-7,24-31'
  hugepages:
    defaultHugepagesSize: 2M
    pages:
      - count: 25600
        node: 0
        size: 2M
      - count: 25600
        node: 1
        size: 2M
  machineConfigPoolSelector:
    pools.operator.machineconfiguration.openshift.io/worker: ''
  nodeSelector:
    node-role.kubernetes.io/worker: ''
  numa:
    topologyPolicy: single-numa-node
  realTimeKernel:
    enabled: false
  workloadHints:
    highPowerConsumption: false
    perPodPowerManagement: false
    realTime: false



spec:
  cpu:
    isolated: '6-11,19-47'
    reserved: '0-5,12-18'
  hugepages:
    defaultHugepagesSize: 2M
    pages:
      - count: 10240
        node: 0
        size: 2M
      - count: 10240
        node: 1
        size: 2M
  machineConfigPoolSelector:
    pools.operator.machineconfiguration.openshift.io/worker: ''
  nodeSelector:
    node-role.kubernetes.io/worker: ''
  numa:
    topologyPolicy: single-numa-node
  realTimeKernel:
    enabled: false
  workloadHints:
    highPowerConsumption: false
    perPodPowerManagement: false
    realTime: false