apiVersion: performance.openshift.io/v2
kind: PerformanceProfile
metadata:
  name: performance
spec:
  cpu:
    isolated: '6-23,30-47'
    reserved: '0-5,24-29'
  hugepages:
    defaultHugepagesSize: 2M
    pages:
      - count: 25600
        node: 0
        size: 2M
      - count: 25600
        node: 1
        size: 2M
  machineConfigPoolSelector:
    pools.operator.machineconfiguration.openshift.io/worker: ''
  nodeSelector:
    node-role.kubernetes.io/worker: ''
  numa:
    topologyPolicy: best-effort
  realTimeKernel:
    enabled: false
  workloadHints:
    highPowerConsumption: true
    perPodPowerManagement: false
    realTime: true