kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: rhel8-numa-2
  namespace: numa-test
  uid: 386ed535-6d7b-4ea5-ae69-f759d83e00c5
  resourceVersion: '346354'
  creationTimestamp: '2024-06-11T01:34:08Z'
  labels:
    workload.template.kubevirt.io/desktop: 'true'
    app.kubernetes.io/part-of: hyperconverged-cluster
    template.kubevirt.io/version: v0.27.0
    app.kubernetes.io/version: 4.15.2
    template.kubevirt.io/type: vm
    vm.kubevirt.io/template: rhel8-numa
    app.kubernetes.io/component: templating
    app.kubernetes.io/managed-by: ssp-operator
    os.template.kubevirt.io/rhel8.0: 'true'
    os.template.kubevirt.io/rhel8.1: 'true'
    os.template.kubevirt.io/rhel8.2: 'true'
    app.kubernetes.io/name: custom-templates
    os.template.kubevirt.io/rhel8.10: 'true'
    os.template.kubevirt.io/rhel8.3: 'true'
    flavor.template.kubevirt.io/large: 'true'
    os.template.kubevirt.io/rhel8.4: 'true'
    os.template.kubevirt.io/rhel8.5: 'true'
    vm.kubevirt.io/template.namespace: numa-test
    os.template.kubevirt.io/rhel8.6: 'true'
    os.template.kubevirt.io/rhel8.7: 'true'
    os.template.kubevirt.io/rhel8.8: 'true'
    os.template.kubevirt.io/rhel8.9: 'true'
  annotations:
    template.kubevirt.io/provider: ''
    template.kubevirt.io/provider-url: 'https://www.redhat.com'
    template.kubevirt.io/containerdisks: |
      registry.redhat.io/rhel8/rhel-guest-image
    template.kubevirt.io/version: v1alpha1
    openshift.io/display-name: Red Hat Enterprise Linux 8 VM - numa2
    openshift.io/documentation-url: 'https://github.com/kubevirt/common-templates'
    template.kubevirt.io/images: |
      https://access.redhat.com/downloads/content/479/ver=/rhel---8/8.6/x86_64/product-software
    operator-sdk/primary-resource-type: SSP.ssp.kubevirt.io
    defaults.template.kubevirt.io/disk: rootdisk
    name.os.template.kubevirt.io/rhel8.0: Red Hat Enterprise Linux 8.0 or higher
    name.os.template.kubevirt.io/rhel8.1: Red Hat Enterprise Linux 8.0 or higher
    name.os.template.kubevirt.io/rhel8.2: Red Hat Enterprise Linux 8.0 or higher
    template.kubevirt.io/editable: |
      /objects[0].spec.template.spec.domain.cpu.sockets
      /objects[0].spec.template.spec.domain.cpu.cores
      /objects[0].spec.template.spec.domain.cpu.threads
      /objects[0].spec.template.spec.domain.memory.guest
      /objects[0].spec.template.spec.domain.devices.disks
      /objects[0].spec.template.spec.volumes
      /objects[0].spec.template.spec.networks
    template.openshift.io/bindable: 'false'
    name.os.template.kubevirt.io/rhel8.3: Red Hat Enterprise Linux 8.0 or higher
    openshift.kubevirt.io/pronounceable-suffix-for-name-expression: 'true'
    operator-sdk/primary-resource: openshift-cnv/ssp-kubevirt-hyperconverged
    name.os.template.kubevirt.io/rhel8.4: Red Hat Enterprise Linux 8.0 or higher
    name.os.template.kubevirt.io/rhel8.5: Red Hat Enterprise Linux 8.0 or higher
    tags: 'hidden,kubevirt,virtualmachine,linux,rhel'
    name.os.template.kubevirt.io/rhel8.6: Red Hat Enterprise Linux 8.0 or higher
    name.os.template.kubevirt.io/rhel8.7: Red Hat Enterprise Linux 8.0 or higher
    template.kubevirt.io/provider-support-level: Full
    name.os.template.kubevirt.io/rhel8.8: Red Hat Enterprise Linux 8.0 or higher
    name.os.template.kubevirt.io/rhel8.9: Red Hat Enterprise Linux 8.0 or higher
    name.os.template.kubevirt.io/rhel8.10: Red Hat Enterprise Linux 8.0 or higher
    description: Template for Red Hat Enterprise Linux 8 VM or newer. A PVC with the RHEL disk image must be available.
    openshift.io/support-url: 'https://github.com/kubevirt/common-templates/issues'
    iconClass: icon-rhel
    openshift.io/provider-display-name: ''
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: template.openshift.io/v1
      time: '2024-06-11T01:34:35Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:template.kubevirt.io/editable': {}
            'f:operator-sdk/primary-resource': {}
            'f:operator-sdk/primary-resource-type': {}
            'f:defaults.template.kubevirt.io/disk': {}
            'f:name.os.template.kubevirt.io/rhel8.0': {}
            'f:template.kubevirt.io/provider-support-level': {}
            'f:name.os.template.kubevirt.io/rhel8.1': {}
            'f:description': {}
            'f:name.os.template.kubevirt.io/rhel8.10': {}
            'f:name.os.template.kubevirt.io/rhel8.2': {}
            'f:template.openshift.io/bindable': {}
            'f:name.os.template.kubevirt.io/rhel8.3': {}
            'f:name.os.template.kubevirt.io/rhel8.4': {}
            'f:iconClass': {}
            'f:openshift.kubevirt.io/pronounceable-suffix-for-name-expression': {}
            'f:name.os.template.kubevirt.io/rhel8.5': {}
            'f:name.os.template.kubevirt.io/rhel8.6': {}
            'f:tags': {}
            .: {}
            'f:name.os.template.kubevirt.io/rhel8.7': {}
            'f:template.kubevirt.io/provider': {}
            'f:name.os.template.kubevirt.io/rhel8.8': {}
            'f:template.kubevirt.io/provider-url': {}
            'f:name.os.template.kubevirt.io/rhel8.9': {}
            'f:template.kubevirt.io/containerdisks': {}
            'f:openshift.io/support-url': {}
            'f:openshift.io/provider-display-name': {}
            'f:template.kubevirt.io/images': {}
            'f:openshift.io/display-name': {}
            'f:template.kubevirt.io/version': {}
            'f:openshift.io/documentation-url': {}
          'f:labels':
            'f:os.template.kubevirt.io/rhel8.0': {}
            'f:os.template.kubevirt.io/rhel8.1': {}
            'f:os.template.kubevirt.io/rhel8.2': {}
            'f:os.template.kubevirt.io/rhel8.3': {}
            'f:flavor.template.kubevirt.io/large': {}
            'f:os.template.kubevirt.io/rhel8.4': {}
            'f:vm.kubevirt.io/template.namespace': {}
            'f:app.kubernetes.io/managed-by': {}
            'f:os.template.kubevirt.io/rhel8.5': {}
            'f:os.template.kubevirt.io/rhel8.6': {}
            'f:os.template.kubevirt.io/rhel8.7': {}
            'f:os.template.kubevirt.io/rhel8.8': {}
            'f:os.template.kubevirt.io/rhel8.9': {}
            'f:os.template.kubevirt.io/rhel8.10': {}
            'f:app.kubernetes.io/name': {}
            .: {}
            'f:workload.template.kubevirt.io/desktop': {}
            'f:app.kubernetes.io/part-of': {}
            'f:app.kubernetes.io/version': {}
            'f:template.kubevirt.io/type': {}
            'f:vm.kubevirt.io/template': {}
            'f:template.kubevirt.io/version': {}
            'f:app.kubernetes.io/component': {}
        'f:objects': {}
        'f:parameters': {}
objects:
  - apiVersion: kubevirt.io/v1
    kind: VirtualMachine
    metadata:
      annotations:
        vm.kubevirt.io/validations: |
          [
            {
              "name": "minimal-required-memory",
              "path": "jsonpath::.spec.domain.memory.guest",
              "rule": "integer",
              "message": "This VM requires more memory.",
              "min": 1610612736
            }
          ]
      labels:
        app: '${NAME}'
        vm.kubevirt.io/template: rhel8-numa-2
        vm.kubevirt.io/template.revision: '1'
        vm.kubevirt.io/template.namespace: numa-test
      name: '${NAME}'
    spec:
      dataVolumeTemplates:
        - apiVersion: cdi.kubevirt.io/v1beta1
          kind: DataVolume
          metadata:
            name: '${NAME}'
          spec:
            sourceRef:
              kind: DataSource
              name: '${DATA_SOURCE_NAME}'
              namespace: '${DATA_SOURCE_NAMESPACE}'
            storage:
              resources:
                requests:
                  storage: 30Gi
      running: false
      template:
        metadata:
          annotations:
            vm.kubevirt.io/flavor: large
            vm.kubevirt.io/os: rhel8
            vm.kubevirt.io/workload: desktop
          labels:
            kubevirt.io/domain: '${NAME}'
            kubevirt.io/size: large
        spec:
          domain:
            cpu:
              cores: 16
              sockets: 1
              threads: 1
              dedicatedCpuPlacement: true
            devices:
              disks:
                - disk:
                    bus: virtio
                  name: rootdisk
                - disk:
                    bus: virtio
                  name: cloudinitdisk
              inputs:
                - bus: virtio
                  name: tablet
                  type: tablet
              interfaces:
                - masquerade: {}
                  model: virtio
                  name: default
              networkInterfaceMultiqueue: true
              rng: {}
            machine:
              type: pc-q35-rhel9.2.0
            memory:
              guest: 19Gi
              hugepages:
                pageSize: 2Mi
          networks:
            - name: default
              pod: {}
          terminationGracePeriodSeconds: 180
          volumes:
            - dataVolume:
                name: '${NAME}'
              name: rootdisk
            - cloudInitNoCloud:
                userData: |-
                  #cloud-config
                  user: cloud-user
                  password: ${CLOUD_USER_PASSWORD}
                  chpasswd: { expire: False }
              name: cloudinitdisk
parameters:
  - name: NAME
    description: VM name
    generate: expression
    from: 'rhel8-[a-z0-9]{16}'
  - name: DATA_SOURCE_NAME
    description: Name of the DataSource to clone
    value: rhel8
  - name: DATA_SOURCE_NAMESPACE
    description: Namespace of the DataSource
    value: openshift-virtualization-os-images
  - name: CLOUD_USER_PASSWORD
    description: Randomized password for the cloud-init user cloud-user
    generate: expression
    from: '[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}'
