apiVersion: v1
kind: Secret
metadata:
  name: logging-loki-s3
  namespace: openshift-logging
stringData:
  access_key_id: 8YVQ7DLS4W64OBRL9VQR
  access_key_secret: aE31wI6PjkEQFIUT7rTxTVvBJUinxtGUhxYX17Gk
  bucketnames: loki-s3-1b092f31-4704-44f8-94d4-00fee4cab9f2
  endpoint: https://rook-ceph-rgw-ocs-storagecluster-cephobjectstore.openshift-storage.svc:443