apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: team-a-cq
spec:
  namespaceSelector: {}
  queueingStrategy: BestEffortFIFO
  cohort: team-ab
  preemption:
    reclaimWithinCohort: Any
  fairSharing:
    weight: 2
  resourceGroups:
  - coveredResources: 
    - cpu
    - memory
    flavors:
    - name: "default-flavor"
      resources:
      - name: "cpu"
        nominalQuota: 10
      - name: "memory"
        nominalQuota: 32Gi
  - coveredResources:
    - nvidia.com/gpu
    flavors:
    - name: gpu-flavor
      resources:
      - name: nvidia.com/gpu
        nominalQuota: "8"
  