apiVersion: apps/v1
kind: Deployment
metadata:
  name: best-effort
  labels:
    app: stress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress
  template:
    metadata:
      labels:
        app: stress
    spec:
      nodeSelector:
        qos-node: 'true'
      containers:
      - name: stress
        image: quay.io/kako1/stress:22
        ports:
        - containerPort: 8080
        imagePullPolicy: Always