apiVersion: apps/v1
kind: Deployment
metadata:
  name: high-priority
  labels:
    app: stress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress
  template:
    metadata:
      labels:
        app: stress
    spec:
      priorityClassName: high-priority
      nodeSelector:
        qos-node: 'true'
      containers:
      - name: httpd
        image: quay.io/kako1/stress:22
        resources:
          requests:
            memory: "5Gi"
            cpu: "2"
          limits:
            memory: "5Gi"
            cpu: "2"
        ports:
        - containerPort: 8080
        imagePullPolicy: Always