apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: acm-observability-450cb847-3f58-464e-b939-4d6ef9540058
      endpoint: s3-openshift-storage.apps.hub.redhatkrsa.com
      insecure: false
      access_key: 1
      secret_key: 1