apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: httpd-pvc-snapshot
  namespace: httpd
spec:
  source:
    persistentVolumeClaimName: httpd-pvc
  volumeSnapshotClassName: csi-vsphere-vsc